### ISSUE TITLE
标签筛选显示不完整

### ISSUE THREAD

**Issue by MichaelMai2000** [fffonion/xeHentai-webui#1]
![image](https://user-images.githubusercontent.com/10582944/45929043-f7dc6200-bf7e-11e8-882c-02a77d1cc289.png)
希望能把筛选tag的菜单完善一下。比如可以下拉并完全显示，加入搜索tag功能等。
谢谢~

**Comment by fffonion** [comment]
ojbk，element ui好像没有提供这个功能，我看能不能撸一个出来

**Comment by fffonion** [comment]
新版已添加独立的搜索框，可以搜索标题和tag ：）
如有问题请重新打开issue
